apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  labels:
    app: {{ .Values.container.name }}
    version: {{ .Values.container.version }}
    environment: {{ .Values.environment }}
  namespace: {{ .Values.container.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
      version: {{ .Values.container.version }}
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
        version: {{ .Values.container.version }}
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.port }}
          protocol: TCP
          name: http
        env:
        - name: environment
          value: {{ .Values.environment }}
