apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service
  labels:
    app: {{ .Values.container.name }}
    version: {{ .Values.container.version }}
  namespace: {{ .Values.container.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.container.name }}
  ports:
  - port: {{ .Values.container.port }}
    name: http
